context:
  name: sqruff
  version: "0.24.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/quarylabs/sqruff/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 465f67fb722d32f28d7aa70a3ecd7261542193757f07d40b32825f71d9165c1b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - cargo-bundle-licenses

tests:
  - script:
      - sqruff --help

about:
  homepage: https://github.com/quarylabs/sqruff
  summary: Fast SQL formatter/linter
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
