context:
  name: sqruff
  version: "0.24.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/quarylabs/sqruff/archive/refs/tags/v${{ version }}.tar.gz
  sha256: c43640473408df8c7c9d948444c8193b119c3bb3860940512841f80a4b021cd9

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - cargo-bundle-licenses

tests:
  - script:
      - sqruff --help

about:
  homepage: https://github.com/quarylabs/sqruff
  summary: Fast SQL formatter/linter
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
