context:
  name: sqruff
  version: "0.25.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/quarylabs/sqruff/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2f8306d3c7d15a2135f473272618b20d7720b0177ac70d1832d9170dfcf45959

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - cargo-bundle-licenses

tests:
  - script:
      - sqruff --help

about:
  homepage: https://github.com/quarylabs/sqruff
  summary: Fast SQL formatter/linter
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
